name: Documentation

on:
  push:
    branches:
      - main
    tags: ['*']
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  build:
    permissions:
      contents: write
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: '1'
      - name: Configure doc environment
        shell: julia --project=docs/ {0}
        run: |
          using Pkg
          Pkg.develop(PackageSpec(path=pwd()))
          Pkg.instantiate()
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-docdeploy@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run doctests
        shell: julia --project=docs/ {0}
        run: |
          using Documenter: DocMeta, doctest
          using LDPCDecoders
          DocMeta.setdocmeta!(LDPCDecoders, :DocTestSetup, :(using LDPCDecoders); recursive=true)
          doctest(LDPCDecoders)
